server:
  port: 8080
  ssl:
    enabled: ${SSL_ENABLED:false}
    key-store: ${SSL_KEY_STORE:}
    key-store-password: ${SSL_KEY_STORE_PASSWORD:}
    key-store-type: ${SSL_KEY_STORE_TYPE:PKCS12}

spring:
  application:
    name: dota-admin-backend
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  # Datasource for local Postgres (matches docker.yml)
  datasource:
    url: jdbc:postgresql://localhost:5432/dota_admin
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true  # Role 테이블 마이그레이션을 위해 활성화
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME:dotapilot1@gmail.com} # Gmail 주소
    password: ${EMAIL_PASSWORD:kicpvsrdpnrlpcrb} # Gmail 앱 비밀번호
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# You can override these values per-profile, e.g. application-dev.yml or
# by setting SPRING_DATASOURCE_URL, SPRING_DATASOURCE_USERNAME, etc. in
# your environment or container.

app:
  jwt:
    secret: ${JWT_SECRET:mySecretKey123456789012345678901234567890123456789012345678901234567890}
    expiration: 86400000 # 24 hours in milliseconds
  data:
    load-initial-users: false # Set to true to load initial test users on startup
  roles:
    autocreate: true
  users:
    autocreate: true
    admin:
      username: ${APP_USERS_ADMIN_USERNAME:terecal}
      email: ${APP_USERS_ADMIN_EMAIL:terecal@daum.net}
      password: ${APP_USERS_ADMIN_PASSWORD:123456}
  registration:
    first-user-admin: true

notification:
  email:
    admin: ${ADMIN_EMAIL:dotapilot1@gmail.com} # 관리자 이메일
    enabled: true # 이메일 알림 활성화/비활성화

kakao:
  api:
    key: ${KAKAO_API_KEY:} # 카카오 REST API 키 (환경변수에서 설정)

logging:
  level:
    root: INFO
  "com.company.dotaadminbackend": DEBUG # 애플리케이션 비즈니스 로그
  "org.springframework.security": INFO  # 필요한 경우 DEBUG
  "org.hibernate.SQL": DEBUG            # 실행되는 SQL 확인
  "org.hibernate.type.descriptor.sql.BasicBinder": TRACE # 바인드 파라미터

